#define leftFrontPort 8
#define leftMidPort 9
#define leftBackPort 10
#define rightFrontPort 7
#define rightMidPort 6
#define rightBackPort 5
#define cataPort 11
#define intakePort 1
#define rotationPort 0